version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: dev
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: dev
    labels:
      - dependencies
